export const ADD_JOURNAL = 'ADD_JOURNAL'
export const ADD_JOURNAL_SUCCESS = 'ADD_JOURNAL_SUCCESS'
export const ADD_JOURNAL_ERROR = 'ADD_JOURNAL_ERROR'

export const UPDATE_JOURNAL = 'UPDATE_JOURNAL'
export const UPDATE_JOURNAL_SUCCESS = 'UPDATE_JOURNAL_SUCCESS'
export const UPDATE_JOURNAL_ERROR = 'UPDATE_JOURNAL_ERROR'

export const GET_JOURNAL = 'GET_JOURNAL'

export const GET_ALL_JOURNALS = 'GET_ALL_JOURNALS'
export const GET_ALL_JOURNALS_SUCCESS = 'GET_ALL_JOURNALS_SUCCESS'
export const GET_ALL_JOURNALS_ERROR = 'GET_ALL_JOURNALS_ERROR'

export const DELETE_JOURNAL = 'DELETE_JOURNAL'
export const DELETE_JOURNAL_SUCCESS = 'DELETE_JOURNAL_SUCCESS'
export const DELETE_JOURNAL_ERROR = 'DELETE_JOURNAL_ERROR'